import type { Program, ProgramCategory, StudyFormat } from './types'

/**
 * Program catalogue (demo). Each entry becomes a program page at /programs/{level}/{slug}/ and a
 * Course in structured data. Start dates and entry requirements are placeholders to confirm.
 */
export const categories: ProgramCategory[] = ['Undergraduate', 'Postgraduate', 'Professional', 'Online', 'Short Courses']

export const categoryBlurb: Record<ProgramCategory, string> = {
  Undergraduate: 'Three- and four-year degrees with studio, lab and placement options.',
  Postgraduate: 'Master’s programs for specialists, career-changers and researchers.',
  Professional: 'Part-time certificates and executive programs built around work.',
  Online: 'Fully online, tutor-supported programs you can study from anywhere.',
  'Short Courses': 'Evening, weekend and summer courses to try something new.',
}

export const formats: StudyFormat[] = ['On campus', 'Blended', 'Online']

export const programs: Program[] = [
  {
    slug: 'applied-computing',
    name: 'Applied Computing',
    award: 'BSc (Hons)',
    category: 'Undergraduate',
    subject: 'Computing',
    duration: '3 years · 4 with placement',
    isoDuration: 'P3Y',
    format: 'On campus',
    studyMode: 'Full-time',
    start: '[[September 2027]]',
    summary: 'A studio-based degree where you learn to design, build and test software with real people in mind.',
    overview: [
      'Applied Computing is taught in studios, not just lecture theatres. From your first term you work in small teams on briefs set with local organisations, learning programming, interface design and data skills by building things that have to work for someone.',
      'Alongside the core, you choose a specialist strand in your second year and can spend a year in industry before your final-year project.',
    ],
    highlights: ['Studio project every term', 'Briefs co-written with partner organisations', 'Optional placement year', 'Small tutorial groups'],
    modules: ['Programming Foundations', 'Human-Centred Design', 'Data & Databases', 'Web & Mobile Systems', 'Software Engineering Studio', 'Final-Year Project'],
    pathways: ['Software development', 'User experience & interface design', 'Data analysis', 'Further study & research'],
    entry: '[[Typical offer and subject requirements to be confirmed by Admissions]]',
    image: { scene: 'studio', mood: 'day', alt: 'Students around a studio table sketching app screens beside a wall of pinned prototypes' },
    featured: true,
    keywords: ['software', 'coding', 'programming', 'computer science', 'ux', 'design', 'data', 'tech', 'it'],
  },
  {
    slug: 'design-digital-media',
    name: 'Design & Digital Media',
    award: 'BA (Hons)',
    category: 'Undergraduate',
    subject: 'Design',
    duration: '3 years',
    isoDuration: 'P3Y',
    format: 'On campus',
    studyMode: 'Full-time',
    start: '[[September 2027]]',
    summary: 'Visual communication, motion and interactive media, taught by practising designers in open studios.',
    overview: [
      'Develop a distinctive creative practice across print, screen and space. You will work in open studios with access to print workshops, a photography suite and motion-capture equipment.',
      'Each year ends with a public exhibition of student work.',
    ],
    highlights: ['24/7 studio access', 'Annual public exhibition', 'Live briefs with cultural partners', 'Portfolio reviews each term'],
    modules: ['Visual Language', 'Typography & Layout', 'Motion & Sound', 'Interactive Media', 'Professional Practice', 'Major Project'],
    pathways: ['Graphic & brand design', 'Motion and moving image', 'Digital product design', 'Creative direction'],
    entry: '[[Portfolio and entry requirements to be confirmed by Admissions]]',
    image: { scene: 'workshop', mood: 'evening', alt: 'Print and making workshop in the evening with a student building a model', align: 'right' },
    keywords: ['art', 'graphic design', 'animation', 'creative', 'media', 'visual', 'illustration'],
  },
  {
    slug: 'environmental-science',
    name: 'Environmental Science',
    award: 'BSc (Hons)',
    category: 'Undergraduate',
    subject: 'Science',
    duration: '3 years · 4 with placement',
    isoDuration: 'P3Y',
    format: 'On campus',
    studyMode: 'Full-time',
    start: '[[September 2027]]',
    summary: 'Field, lab and data skills to understand — and help restore — the places we live.',
    overview: [
      'Spend time every term in the field, from river catchments to urban green spaces, and learn to turn observations into evidence in our environmental labs.',
      'Projects are often shared with community groups and local authorities.',
    ],
    highlights: ['Fieldwork every term', 'Modern teaching labs', 'Community research projects', 'GIS and data-science training'],
    modules: ['Earth Systems', 'Ecology in Practice', 'Environmental Chemistry', 'GIS & Remote Sensing', 'Climate & Society', 'Dissertation'],
    pathways: ['Environmental consultancy', 'Conservation & land management', 'Policy and planning', 'Postgraduate research'],
    entry: '[[Entry requirements to be confirmed by Admissions]]',
    image: { scene: 'lab', mood: 'morning', alt: 'Bright teaching lab with students examining water samples at a bench' },
    keywords: ['ecology', 'climate', 'biology', 'geography', 'sustainability', 'environment', 'chemistry'],
  },
  {
    slug: 'business-social-enterprise',
    name: 'Business & Social Enterprise',
    award: 'BA (Hons)',
    category: 'Undergraduate',
    subject: 'Business',
    duration: '3 years',
    isoDuration: 'P3Y',
    format: 'Blended',
    studyMode: 'Full-time',
    start: '[[September 2027]]',
    summary: 'Learn how organisations work — and how to start one that does some good.',
    overview: [
      'Combine core business disciplines with hands-on enterprise: you will develop, test and pitch a venture with a team, supported by mentors from our alumni and partner network.',
    ],
    highlights: ['Venture studio in year two', 'Mentors from partner organisations', 'Blended timetable', 'Optional study-abroad term'],
    modules: ['Organisations & People', 'Finance for Decision-Making', 'Marketing in Practice', 'Social Innovation', 'Venture Studio', 'Strategy'],
    pathways: ['Management & operations', 'Starting a venture', 'Non-profit and public sector', 'Consulting'],
    entry: '[[Entry requirements to be confirmed by Admissions]]',
    image: { scene: 'community', mood: 'day', alt: 'Students running a community garden project with local residents' },
    keywords: ['management', 'entrepreneurship', 'startup', 'economics', 'marketing', 'finance', 'nonprofit'],
  },
  {
    slug: 'data-science-society',
    name: 'Data Science & Society',
    award: 'MSc',
    category: 'Postgraduate',
    subject: 'Computing',
    duration: '1 year full-time · 2 years part-time',
    isoDuration: 'P1Y',
    format: 'Blended',
    studyMode: 'Full-time or part-time',
    start: '[[September 2027 · January 2028]]',
    summary: 'Statistical, computational and ethical foundations for working responsibly with data.',
    overview: [
      'Designed for graduates from any discipline, this master’s builds strong technical skills in programming, statistics and machine learning alongside the ethical and social questions data work raises.',
    ],
    highlights: ['Open to all first-degree subjects', 'Evening and weekend teaching blocks', 'Applied capstone with a partner', 'Responsible-AI focus'],
    modules: ['Programming for Data', 'Statistical Modelling', 'Machine Learning', 'Data Ethics & Governance', 'Visualisation & Storytelling', 'Capstone Project'],
    pathways: ['Data analysis & science', 'Research and policy', 'Public-sector analytics', 'Doctoral study'],
    entry: '[[Normally a first degree in any subject — confirm with Admissions]]',
    image: { scene: 'digital', mood: 'evening', alt: 'Student analysing a chart on a laptop at a desk in the library' },
    keywords: ['data', 'ai', 'machine learning', 'statistics', 'analytics', 'python', 'masters'],
  },
  {
    slug: 'education-learning-design',
    name: 'Education & Learning Design',
    award: 'MA',
    category: 'Postgraduate',
    subject: 'Education',
    duration: '1 year full-time · 2 years part-time',
    isoDuration: 'P1Y',
    format: 'Online',
    studyMode: 'Full-time or part-time',
    start: '[[September 2027]]',
    summary: 'For teachers, trainers and designers shaping how people learn — in classrooms and online.',
    overview: ['Explore learning science, curriculum design and digital pedagogy, and apply them directly to your own teaching or training context.'],
    highlights: ['Fully online with live seminars', 'Practice-based assignments', 'Personal academic tutor', 'Flexible part-time route'],
    modules: ['How People Learn', 'Curriculum Design', 'Digital Pedagogy', 'Assessment for Learning', 'Research Methods', 'Dissertation'],
    pathways: ['Teaching & leadership', 'Instructional & learning design', 'Training and development', 'Educational research'],
    entry: '[[Entry requirements to be confirmed by Admissions]]',
    image: { scene: 'seminar', mood: 'day', alt: 'Small seminar group in discussion around a table by a tall window' },
    keywords: ['teaching', 'pedagogy', 'learning design', 'instructional design', 'training', 'masters', 'teacher'],
  },
  {
    slug: 'sustainable-engineering',
    name: 'Sustainable Engineering',
    award: 'MSc',
    category: 'Postgraduate',
    subject: 'Engineering',
    duration: '1 year full-time',
    isoDuration: 'P1Y',
    format: 'On campus',
    studyMode: 'Full-time',
    start: '[[September 2027]]',
    summary: 'Design energy, materials and infrastructure systems for a low-carbon future.',
    overview: ['A hands-on master’s using our engineering workshop and prototyping lab, with a group design project and an individual research project.'],
    highlights: ['Prototyping lab access', 'Group design project', 'Lifecycle & carbon analysis', 'Guest practitioners every term'],
    modules: ['Energy Systems', 'Sustainable Materials', 'Lifecycle Assessment', 'Systems Modelling', 'Group Design Project', 'Research Project'],
    pathways: ['Engineering design', 'Energy & infrastructure', 'Sustainability consulting', 'Research'],
    entry: '[[Normally a first degree in engineering or a related subject — confirm with Admissions]]',
    image: { scene: 'workshop', mood: 'day', alt: 'Engineering workshop with a student assembling a prototype at a workbench' },
    keywords: ['engineering', 'energy', 'renewables', 'climate', 'materials', 'infrastructure', 'masters'],
  },
  {
    slug: 'project-leadership',
    name: 'Project Leadership',
    award: 'Professional Certificate',
    category: 'Professional',
    subject: 'Leadership',
    duration: '6 months · part-time',
    isoDuration: 'P6M',
    format: 'Blended',
    studyMode: 'Part-time',
    start: '[[Every January, May and September]]',
    summary: 'Plan, lead and deliver complex projects with confidence — studied around your job.',
    overview: ['Monthly on-campus workshops combined with online learning and a workplace project that applies each module to your own organisation.'],
    highlights: ['Monthly Saturday workshops', 'Apply learning to a live work project', 'Peer learning group', 'Can count toward a master’s [[confirm credit transfer]]'],
    modules: ['Project Foundations', 'Leading Teams', 'Risk & Stakeholders', 'Agile & Hybrid Delivery', 'Workplace Project'],
    pathways: ['Project & programme management', 'Operations leadership', 'Team leadership'],
    entry: '[[Normally two years’ work experience — confirm with Admissions]]',
    image: { scene: 'seminar', mood: 'evening', alt: 'Working professionals in an evening workshop around a seminar table', align: 'right' },
    keywords: ['project management', 'leadership', 'management', 'agile', 'professional', 'cpd', 'part-time'],
  },
  {
    slug: 'leading-through-change',
    name: 'Leading Through Change',
    award: 'Executive Program',
    category: 'Professional',
    subject: 'Leadership',
    duration: '5 days · intensive',
    isoDuration: 'P5D',
    format: 'On campus',
    studyMode: 'Intensive',
    start: '[[March and October cohorts]]',
    summary: 'A five-day executive program for senior leaders navigating organisational change.',
    overview: ['Small cohorts of senior leaders work through case studies, simulations and coaching to build a practical change plan for their own organisation.'],
    highlights: ['Cohorts of up to 24', 'One-to-one coaching session', 'Case studies and simulations', 'Follow-up alumni circle'],
    modules: ['Leading Self', 'Culture & Change', 'Decision-Making Under Uncertainty', 'Your Change Plan'],
    pathways: ['Senior leadership', 'Organisational change', 'Board and executive roles'],
    entry: '[[Senior-level experience — confirm with Admissions]]',
    image: { scene: 'lecture', mood: 'day', alt: 'Executive education session in a lecture room with a speaker presenting' },
    keywords: ['executive education', 'leadership', 'change management', 'strategy', 'senior'],
  },
  {
    slug: 'ux-research',
    name: 'UX Research',
    award: 'Online Certificate',
    category: 'Online',
    subject: 'Design',
    duration: '12 weeks · 6–8 hrs/week',
    isoDuration: 'P12W',
    format: 'Online',
    studyMode: 'Part-time',
    start: '[[Monthly intakes]]',
    summary: 'Plan and run user research that changes product decisions, with weekly tutor feedback.',
    overview: ['Learn interviewing, usability testing and synthesis by running a real research project from first question to final presentation.'],
    highlights: ['Weekly live tutor sessions', 'Real research project', 'Peer critique groups', 'Study anywhere'],
    modules: ['Research Questions', 'Interviewing', 'Usability Testing', 'Synthesis & Insight', 'Communicating Findings'],
    pathways: ['UX research', 'Product design', 'Service design'],
    entry: 'No formal entry requirements.',
    image: { scene: 'digital', mood: 'day', alt: 'Learner joining a live online class from a laptop at home', align: 'left' },
    keywords: ['ux', 'user research', 'design', 'online', 'product', 'usability'],
  },
  {
    slug: 'digital-marketing',
    name: 'Digital Marketing',
    award: 'Online Diploma',
    category: 'Online',
    subject: 'Business',
    duration: '9 months · part-time',
    isoDuration: 'P9M',
    format: 'Online',
    studyMode: 'Part-time',
    start: '[[January and September]]',
    summary: 'Strategy, content, search and analytics — practical skills you can apply from week one.',
    overview: ['A flexible online diploma with short weekly lessons, live clinics and a final campaign project for a real or simulated client.'],
    highlights: ['Fully online', 'Live weekly clinics', 'Final campaign project', 'Personal tutor'],
    modules: ['Marketing Strategy', 'Content & Social', 'Search & SEO', 'Email & CRM', 'Analytics', 'Campaign Project'],
    pathways: ['Marketing & communications', 'Content strategy', 'Freelance and small business'],
    entry: 'No formal entry requirements.',
    image: { scene: 'digital', mood: 'morning', alt: 'Learner studying online at a kitchen table with a laptop and notebook', align: 'right' },
    keywords: ['marketing', 'seo', 'social media', 'content', 'online', 'advertising', 'analytics'],
  },
  {
    slug: 'introduction-to-python',
    name: 'Introduction to Python',
    award: 'Short Course',
    category: 'Short Courses',
    subject: 'Computing',
    duration: '8 weeks · one evening a week',
    isoDuration: 'P8W',
    format: 'Blended',
    studyMode: 'Part-time',
    start: '[[October · February · April]]',
    summary: 'A friendly first step into programming. No experience needed.',
    overview: ['Learn to write small, useful Python programs in a supportive evening class, with recordings and exercises online.'],
    highlights: ['No experience needed', 'Evening classes', 'Recorded sessions', 'Certificate of completion'],
    modules: ['Python Basics', 'Working with Data', 'Functions & Files', 'A Small Project'],
    pathways: ['Further study in computing', 'Automating everyday work'],
    entry: 'Open to everyone aged 16+.',
    image: { scene: 'library', mood: 'evening', alt: 'Evening class in the library with learners at laptops' },
    keywords: ['python', 'coding', 'programming', 'beginner', 'evening', 'short course'],
  },
  {
    slug: 'academic-english',
    name: 'Academic English for Study',
    award: 'Short Course',
    category: 'Short Courses',
    subject: 'Languages',
    duration: '6 or 10 weeks',
    isoDuration: 'P6W',
    format: 'On campus',
    studyMode: 'Full-time',
    start: '[[July and August]]',
    summary: 'Build the reading, writing and speaking skills to thrive in English-medium study.',
    overview: ['Small classes focused on academic writing, seminar discussion and study skills, with a weekly cultural programme.'],
    highlights: ['Classes of up to 14', 'Placement assessment', 'Weekly cultural programme', 'Progression guidance'],
    modules: ['Academic Writing', 'Seminar Skills', 'Listening & Note-Taking', 'Research Skills'],
    pathways: ['Undergraduate or postgraduate study'],
    entry: '[[English level requirements to be confirmed]]',
    image: { scene: 'seminar', mood: 'morning', alt: 'Language class in conversation around a seminar table', align: 'left' },
    keywords: ['english', 'language', 'esl', 'ielts', 'international', 'pre-sessional', 'language school'],
  },
  {
    slug: 'creative-coding-summer-school',
    name: 'Creative Coding Summer School',
    award: 'Summer School',
    category: 'Short Courses',
    subject: 'Design',
    duration: '2 weeks',
    isoDuration: 'P2W',
    format: 'On campus',
    studyMode: 'Full-time',
    start: '[[July]]',
    summary: 'Two weeks of making interactive art, games and sound with code — for ages 16–18.',
    overview: ['A residential-style summer school that ends with a showcase for friends and family.'],
    highlights: ['Ages 16–18', 'Showcase on the final day', 'Supervised activities', 'No experience needed'],
    modules: ['Code as a Sketchbook', 'Interactive Sound', 'Making a Small Game', 'Showcase'],
    pathways: ['Undergraduate study in computing or design'],
    entry: 'Ages 16–18. No experience needed.',
    image: { scene: 'projects', mood: 'day', alt: 'Students testing an interactive installation they built' },
    keywords: ['summer school', 'coding', 'games', 'art', 'teen', 'young people', 'creative'],
  },
]

export const featuredProgram = programs.find((p) => p.featured) ?? programs[0]
