import type { Property } from './types'

/**
 * Demo listings — fictional properties for the pitch.
 * In production this module is replaced by a property-feed adapter returning `Property[]`.
 */
export const properties: Property[] = [
  {
    id: 'hv-1042',
    slug: 'the-linden-house-riverside',
    title: 'The Linden House',
    address: { line: 'Weir Lane', areaId: 'riverside', city: 'Wrenfield', postcode: 'WR3 2LT' },
    listingType: 'sale',
    status: 'New Instruction',
    propertyType: 'house',
    price: 1450000,
    priceQualifier: 'Guide price',
    bedrooms: 5,
    bathrooms: 4,
    receptions: 3,
    floorArea: 4120,
    plot: '0.42 acres',
    tenure: 'Freehold',
    epc: 'B',
    councilTax: 'Band G',
    summary: 'A contemporary riverside house with a cantilevered upper floor, a walled garden and its own mooring.',
    description: [
      'Set back from Weir Lane behind a screen of pleached limes, The Linden House was designed by a local practice in 2016 and has been carefully kept since. The ground floor opens almost entirely to the garden, with a kitchen and dining room under a long rooflight and a sitting room that looks straight down the lawn to the water.',
      'Upstairs, five bedrooms sit within the timber-clad upper volume, including a principal suite with a dressing room and a balcony over the river. There is a separate studio above the garage, air-source heating throughout and a private mooring on the Wren.',
    ],
    keyFeatures: [
      'Private mooring on the River Wren',
      'Principal suite with river balcony',
      'Walled garden with pleached limes',
      'Studio above double garage',
      'Air-source heat pump & solar array',
      'Twelve minutes’ walk to the Old Town',
    ],
    features: ['garden', 'parking', 'outside-space', 'water-views'],
    images: [
      { scene: 'villa', tone: 'dusk', alt: 'The Linden House at dusk, a two-storey contemporary house with lit glazing and a reflecting pool' },
      { scene: 'interior', tone: 'golden', view: 'garden', alt: 'Open-plan sitting room with floor-to-ceiling glazing onto the garden' },
      { scene: 'kitchen', tone: 'day', alt: 'Kitchen with a long stone island under pendant lights' },
      { scene: 'bedroom', tone: 'golden', alt: 'Principal bedroom with a balcony overlooking the river' },
    ],
    agentId: 'eleanor',
    listedAt: '2026-09-28',
    featured: true,
    mapPosition: { x: 37, y: 66 },
  },
  {
    id: 'hv-1038',
    slug: 'no-7-linden-square-old-town',
    title: 'No. 7 Linden Square',
    address: { line: 'Linden Square', areaId: 'old-town', city: 'Wrenfield', postcode: 'WR1 4LS' },
    listingType: 'sale',
    status: 'For Sale',
    propertyType: 'townhouse',
    price: 1185000,
    priceQualifier: 'Offers over',
    bedrooms: 4,
    bathrooms: 3,
    receptions: 2,
    floorArea: 2870,
    tenure: 'Freehold',
    epc: 'D',
    councilTax: 'Band F',
    summary: 'A Grade II listed Georgian townhouse on the quiet side of Linden Square, with a south-facing walled garden.',
    description: [
      'No. 7 keeps its original shutters, cornicing and a cantilevered stone staircase that rises through four floors. The first-floor drawing room runs the full depth of the house with three tall sash windows over the square.',
      'The lower ground floor has been opened into a kitchen and family room leading to a walled garden with a vaulted store.',
    ],
    keyFeatures: ['Grade II listed', 'First-floor drawing room', 'South-facing walled garden', 'Original shutters & stone stair', 'Residents’ parking'],
    features: ['garden', 'period', 'outside-space'],
    images: [
      { scene: 'townhouse', tone: 'golden', alt: 'Georgian brick townhouse with a black front door, fanlight and railings' },
      { scene: 'interior', tone: 'day', view: 'city', alt: 'Drawing room with tall sash windows' },
      { scene: 'kitchen', tone: 'golden', alt: 'Lower ground floor kitchen' },
    ],
    agentId: 'eleanor',
    listedAt: '2026-09-12',
    mapPosition: { x: 48, y: 46 },
  },
  {
    id: 'hv-1031',
    slug: 'penthouse-the-printworks-city-centre',
    title: 'Penthouse, The Printworks',
    address: { line: 'Foundry Street', areaId: 'city-centre', city: 'Wrenfield', postcode: 'WR1 1PW' },
    listingType: 'sale',
    status: 'For Sale',
    propertyType: 'penthouse',
    price: 895000,
    bedrooms: 3,
    bathrooms: 2,
    receptions: 1,
    floorArea: 1960,
    tenure: 'Share of freehold',
    epc: 'C',
    councilTax: 'Band E',
    summary: 'A top-floor loft in a converted print works, with a wraparound roof terrace and views across the cathedral.',
    description: [
      'The penthouse occupies the whole top floor of The Printworks, with exposed steel trusses, polished concrete floors and a wraparound terrace.',
      'Two parking spaces and a secure store are included in the basement.',
    ],
    keyFeatures: ['Wraparound roof terrace', 'Exposed steel trusses', 'Two secure parking spaces', 'Lift access'],
    features: ['parking', 'outside-space'],
    images: [
      { scene: 'interior', tone: 'dusk', view: 'city', alt: 'Loft living room at dusk with the city skyline through tall windows' },
      { scene: 'skyline', tone: 'dusk', alt: 'View from the roof terrace across the city' },
      { scene: 'kitchen', tone: 'dusk', alt: 'Open kitchen with dark cabinetry' },
    ],
    agentId: 'james',
    listedAt: '2026-09-02',
    mapPosition: { x: 63, y: 33 },
  },
  {
    id: 'hv-1027',
    slug: 'saltmarsh-house-coast',
    title: 'Saltmarsh House',
    address: { line: 'Dune Road, Saltmarsh Bay', areaId: 'coast-country', city: 'Wrenfield', postcode: 'WR9 8SB' },
    listingType: 'sale',
    status: 'Under Offer',
    propertyType: 'house',
    price: 1275000,
    priceQualifier: 'Guide price',
    bedrooms: 4,
    bathrooms: 3,
    receptions: 2,
    floorArea: 2650,
    plot: '0.6 acres',
    tenure: 'Freehold',
    epc: 'B',
    councilTax: 'Band F',
    summary: 'A timber and glass house above the dunes, with direct access to the beach at Saltmarsh Bay.',
    description: ['Saltmarsh House sits just behind the dune line, with the living spaces raised to look over the marram grass to the sea.'],
    keyFeatures: ['Direct beach access', 'Sea views from every bedroom', 'Raised decked terrace', 'Outdoor shower & board store'],
    features: ['garden', 'parking', 'outside-space', 'water-views'],
    images: [
      { scene: 'coastal', tone: 'golden', alt: 'Timber-clad house above the dunes overlooking the sea' },
      { scene: 'interior', tone: 'day', view: 'sea', alt: 'Living room with a wide window onto the sea' },
    ],
    agentId: 'tom',
    listedAt: '2026-08-20',
    mapPosition: { x: 86, y: 80 },
  },
  {
    id: 'hv-1024',
    slug: 'orchard-cottage-hale-green',
    title: 'Orchard Cottage',
    address: { line: 'Church Lane, Hale Green', areaId: 'coast-country', city: 'Wrenfield', postcode: 'WR8 3CL' },
    listingType: 'sale',
    status: 'For Sale',
    propertyType: 'cottage',
    price: 625000,
    bedrooms: 3,
    bathrooms: 2,
    receptions: 2,
    floorArea: 1540,
    plot: '0.3 acres',
    tenure: 'Freehold',
    epc: 'E',
    councilTax: 'Band D',
    summary: 'A stone cottage at the end of a no-through lane, with an old orchard, inglenook fireplace and open views.',
    description: ['Orchard Cottage has been sympathetically extended with a garden room that looks across its own small orchard to the hills.'],
    keyFeatures: ['Inglenook fireplace', 'Established orchard', 'Garden room extension', 'No-through lane'],
    features: ['garden', 'parking', 'period', 'outside-space'],
    images: [
      { scene: 'cottage', tone: 'golden', alt: 'Stone cottage with a pitched roof, chimney and an orchard' },
      { scene: 'countryside', tone: 'day', alt: 'Rolling hills behind the cottage' },
    ],
    agentId: 'tom',
    listedAt: '2026-09-18',
    mapPosition: { x: 77, y: 64 },
  },
  {
    id: 'hv-1019',
    slug: 'apartment-4-northgate-park',
    title: 'Apartment 4, Northgate Park',
    address: { line: 'Northgate Park', areaId: 'north-district', city: 'Wrenfield', postcode: 'WR5 6NP' },
    listingType: 'sale',
    status: 'For Sale',
    propertyType: 'apartment',
    price: 315000,
    bedrooms: 2,
    bathrooms: 2,
    receptions: 1,
    floorArea: 840,
    tenure: 'Leasehold',
    epc: 'A',
    councilTax: 'Band C',
    summary: 'A bright corner apartment overlooking the park, with a deep balcony and an allocated parking space.',
    description: ['A well-planned two-bedroom apartment in one of North District’s most energy-efficient buildings.'],
    keyFeatures: ['Corner aspect over the park', 'Deep south-west balcony', 'Allocated parking', 'EPC A'],
    features: ['parking', 'outside-space', 'new-build'],
    images: [
      { scene: 'apartment', tone: 'day', alt: 'Modern apartment building with balconies beside a park' },
      { scene: 'interior', tone: 'day', view: 'garden', alt: 'Open-plan living space with balcony doors' },
    ],
    agentId: 'james',
    listedAt: '2026-09-25',
    mapPosition: { x: 54, y: 18 },
  },
  {
    id: 'hv-1012',
    slug: 'beech-house-ashgrove',
    title: 'Beech House',
    address: { line: 'The Avenue, Ashgrove', areaId: 'the-suburbs', city: 'Wrenfield', postcode: 'WR6 2AV' },
    listingType: 'sale',
    status: 'Coming Soon',
    propertyType: 'house',
    price: 780000,
    priceQualifier: 'Guide price',
    bedrooms: 5,
    bathrooms: 3,
    receptions: 3,
    floorArea: 2780,
    tenure: 'Freehold',
    epc: 'C',
    councilTax: 'Band F',
    summary: 'An Edwardian family house on Ashgrove’s best-known avenue, with a 120ft garden and a home office.',
    description: ['Beech House has been in the same family for twenty years and comes with a long, private garden and a detached studio.'],
    keyFeatures: ['120ft rear garden', 'Detached garden studio', 'Driveway for two cars', 'Short walk to Ashgrove station'],
    features: ['garden', 'parking', 'period', 'outside-space'],
    images: [
      { scene: 'suburb', tone: 'golden', alt: 'Edwardian family house with a gabled front behind a beech hedge' },
      { scene: 'kitchen', tone: 'day', alt: 'Family kitchen opening onto the garden' },
    ],
    agentId: 'tom',
    listedAt: '2026-10-01',
    mapPosition: { x: 20, y: 33 },
  },
  /* ------------------------------------------------------------ Lettings */
  {
    id: 'hv-2051',
    slug: 'the-boathouse-apartment-riverside',
    title: 'The Boathouse Apartment',
    address: { line: 'Towpath Walk', areaId: 'riverside', city: 'Wrenfield', postcode: 'WR3 1TW' },
    listingType: 'rent',
    status: 'To Let',
    propertyType: 'apartment',
    price: 2150,
    bedrooms: 2,
    bathrooms: 2,
    receptions: 1,
    floorArea: 1080,
    epc: 'B',
    councilTax: 'Band D',
    availableFrom: 'November 2026',
    summary: 'A converted boathouse apartment with a long balcony directly over the water. Available furnished or unfurnished.',
    description: ['Set on the first floor of a converted Victorian boathouse with river views from every room.'],
    keyFeatures: ['Balcony over the river', 'Furnished or unfurnished', 'Bike store', 'Available November'],
    features: ['outside-space', 'water-views', 'furnished'],
    images: [
      { scene: 'riverside', tone: 'day', alt: 'Converted boathouse on the riverbank' },
      { scene: 'interior', tone: 'golden', view: 'sea', alt: 'Living room with a view across the water' },
    ],
    agentId: 'priya',
    listedAt: '2026-09-30',
    mapPosition: { x: 44, y: 60 },
  },
  {
    id: 'hv-2047',
    slug: 'loft-3-the-mill-city-centre',
    title: 'Loft 3, The Mill',
    address: { line: 'Mill Yard', areaId: 'city-centre', city: 'Wrenfield', postcode: 'WR1 2MY' },
    listingType: 'rent',
    status: 'To Let',
    propertyType: 'apartment',
    price: 1650,
    bedrooms: 1,
    bathrooms: 1,
    receptions: 1,
    floorArea: 760,
    epc: 'C',
    councilTax: 'Band C',
    availableFrom: 'Now',
    summary: 'A double-height loft with original mill windows, a mezzanine bedroom and concierge.',
    description: ['A characterful loft in the converted wool mill, two minutes from Station Square.'],
    keyFeatures: ['Double-height living space', 'Mezzanine bedroom', 'Concierge', 'Available now'],
    features: ['furnished', 'pets-considered'],
    images: [
      { scene: 'interior', tone: 'day', view: 'city', alt: 'Double-height loft with large factory windows' },
      { scene: 'skyline', tone: 'day', alt: 'City centre rooftops' },
    ],
    agentId: 'priya',
    listedAt: '2026-09-21',
    mapPosition: { x: 59, y: 39 },
  },
  {
    id: 'hv-2043',
    slug: 'mews-house-cathedral-close-old-town',
    title: 'Cathedral Mews',
    address: { line: 'Cathedral Mews', areaId: 'old-town', city: 'Wrenfield', postcode: 'WR1 3CM' },
    listingType: 'rent',
    status: 'Let Agreed',
    propertyType: 'townhouse',
    price: 2850,
    bedrooms: 3,
    bathrooms: 2,
    receptions: 1,
    floorArea: 1390,
    epc: 'C',
    councilTax: 'Band E',
    availableFrom: 'December 2026',
    summary: 'A cobbled-mews house behind the cathedral close, with a courtyard and integral garage.',
    description: ['A rare mews house to let in the Old Town, newly redecorated throughout.'],
    keyFeatures: ['Private courtyard', 'Integral garage', 'Newly redecorated', 'Quiet mews setting'],
    features: ['parking', 'period', 'outside-space'],
    images: [
      { scene: 'oldtown', tone: 'day', alt: 'Cobbled mews with painted townhouses' },
      { scene: 'bedroom', tone: 'day', alt: 'Bedroom with beamed ceiling' },
    ],
    agentId: 'priya',
    listedAt: '2026-09-05',
    mapPosition: { x: 45, y: 42 },
  },
  {
    id: 'hv-2039',
    slug: 'garden-flat-fenwick-road',
    title: 'Garden Flat, Fenwick Road',
    address: { line: 'Fenwick Road', areaId: 'the-suburbs', city: 'Wrenfield', postcode: 'WR6 4FR' },
    listingType: 'rent',
    status: 'To Let',
    propertyType: 'apartment',
    price: 1395,
    bedrooms: 2,
    bathrooms: 1,
    receptions: 1,
    floorArea: 910,
    epc: 'D',
    councilTax: 'Band C',
    availableFrom: 'Mid October 2026',
    summary: 'A raised ground-floor flat in a Victorian villa with sole use of the rear garden. Pets considered.',
    description: ['Bright, high-ceilinged rooms and a private garden, a short walk from Fenwick village.'],
    keyFeatures: ['Sole use of rear garden', 'Pets considered', 'High ceilings', 'Near Fenwick village'],
    features: ['garden', 'period', 'pets-considered'],
    images: [
      { scene: 'suburb', tone: 'day', alt: 'Victorian villa on a leafy road' },
      { scene: 'interior', tone: 'golden', view: 'garden', alt: 'Living room with bay window' },
    ],
    agentId: 'priya',
    listedAt: '2026-09-27',
    mapPosition: { x: 24, y: 27 },
  },
  {
    id: 'hv-2035',
    slug: 'townhouse-12-northgate-row',
    title: '12 Northgate Row',
    address: { line: 'Northgate Row', areaId: 'north-district', city: 'Wrenfield', postcode: 'WR5 3NR' },
    listingType: 'rent',
    status: 'To Let',
    propertyType: 'townhouse',
    price: 1950,
    bedrooms: 3,
    bathrooms: 2,
    receptions: 1,
    floorArea: 1240,
    epc: 'A',
    councilTax: 'Band D',
    availableFrom: 'November 2026',
    summary: 'A new-build townhouse with a roof terrace, solar panels and an EV charger, close to the tram.',
    description: ['Built in 2025 to a high energy standard, with a family kitchen on the ground floor and a roof terrace.'],
    keyFeatures: ['Roof terrace', 'EV charger', 'Solar PV', 'Two minutes to the tram'],
    features: ['parking', 'outside-space', 'new-build'],
    images: [
      { scene: 'apartment', tone: 'golden', alt: 'Row of modern brick townhouses' },
      { scene: 'kitchen', tone: 'day', alt: 'Bright family kitchen' },
    ],
    agentId: 'priya',
    listedAt: '2026-10-03',
    mapPosition: { x: 58, y: 13 },
  },
  {
    id: 'hv-3008',
    slug: 'studio-offices-foundry-street',
    title: 'Studio Offices, 21 Foundry Street',
    address: { line: 'Foundry Street', areaId: 'city-centre', city: 'Wrenfield', postcode: 'WR1 1FS' },
    listingType: 'rent',
    status: 'To Let',
    propertyType: 'commercial',
    price: 3400,
    bedrooms: 0,
    bathrooms: 2,
    floorArea: 2200,
    epc: 'B',
    availableFrom: 'January 2027',
    summary: 'Open-plan studio offices over two floors of a refurbished warehouse, suited to a creative or professional firm.',
    description: ['Self-contained offices with exposed brick, meeting rooms and a shared courtyard.'],
    keyFeatures: ['Self-contained over two floors', 'Two meeting rooms', 'Shared courtyard', 'Cycle storage & showers'],
    features: ['outside-space'],
    images: [
      { scene: 'office', tone: 'day', alt: 'Refurbished warehouse office building with large windows' },
      { scene: 'interior', tone: 'day', view: 'city', alt: 'Open-plan studio office' },
    ],
    agentId: 'james',
    listedAt: '2026-09-15',
    mapPosition: { x: 65, y: 31 },
  },
]

export const getProperty = (id: string) => properties.find((p) => p.id === id)

/** The listing promoted in the editorial "Featured Residence" section. */
export const showcaseProperty = properties.find((p) => p.featured) ?? properties[0]
